---
apiVersion: v1
kind: Secret
metadata:
  name: jbuck-t4-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-ms/jbuck-t4-gateway-gitops
